### ISSUE TITLE
匠魂联动中下界合金的超级强化词条缺少翻译

### ISSUE THREAD

**Issue by ghost** [037-Development-Group/NetheriteRoad#2]
如图
![QQ截图20221105093029](https://user-images.githubusercontent.com/103164772/200095142-abe8f123-0a0e-4ad1-88bc-b5da1da72630.png)

**Comment by Layaot** [comment]
已经收到，预计会在0.1.2版本处理并修复

**Comment by Layaot** [comment]
> 已经收到，预计会在0.1.2版本处理并修复

说错了，是1.1.2

**Comment by Layaot** [comment]
已修复
